### ISSUE TITLE
Running content scripts in the main JavaScript world throws an error

### ISSUE THREAD

**Issue by cezaraugusto** [awesome-webextension/webpack-target-webextension#44]
Hello there! First off, thanks for such a great plugin! I'm using it as a dependency for my project and had a user report that it errors when running scripts in the main world (ref: https://github.com/cezaraugusto/extension.js/issues/66). While investigating it seems that the root cause is a  check for `chrome.*` and `browser.*` namespaces in https://github.com/awesome-webextension/webpack-target-webextension/blob/master/lib/webpack5/BrowserRuntime.js#L8.

Client error:

<img width="534" alt="Screenshot 2024-06-05 at 16 27 06" src="https://github.com/awesome-webextension/webpack-target-webextension/assets/4672033/6812edaa-41a1-4b01-a40e-949e3923304c">

Referenced file:

<img width="792" alt="Screenshot 2024-06-05 at 16 27 15" src="https://github.com/awesome-webextension/webpack-target-webextension/assets/4672033/0fd53bed-cac5-493c-ae1b-4ec4b5ed7b6b">

I created a repo with a reproducible sample at https://github.com/cezaraugusto/main-world-extension, but seems that just adding the field to the manifest file is enough to repro.

```diff
// manifest.json
{
  "manifest_version": 3,
  "version": "1.0",
  "name": "main-world-extension",
  "description": "An extension running in the main world.",
  "background": {
    "service_worker": "./dist/background.js"
  },
  "content_scripts": [
    {
+      "world": "MAIN",
      "matches": [
        "https://extension.js.org/*"
      ],
      "js": [
        "./dist/content.js"
      ]
    }
  ]
}
```

**Comment by Jack-Works** [comment]
hi @cezaraugusto, can you try to [enable ES Module loader](https://github.com/awesome-webextension/webpack-target-webextension?tab=readme-ov-file#content-script) and [disable runtime check](https://github.com/awesome-webextension/webpack-target-webextension?tab=readme-ov-file#optionsweakruntimecheck)? For a MAIN world script, only ESM Module loader can share code with the main chunk.

Let me know if you need help!

**Comment by cezaraugusto** [comment]
I've tried setting `weakRuntimeCheck` to false and set `"type": "module"` to package.json. Here's my webpack config so far, couldn't make it work unfortunately. 

Also updated the sample repo: https://github.com/cezaraugusto/main-world-extension:

```js
import WebExtension from "webpack-target-webextension";
import webpack from "webpack";
import { join } from "path";
import { fileURLToPath } from "url";
import {dirname} from "path";

// Get the file path from the URL
const __filename = fileURLToPath(import.meta.url);

// Get the directory name from the file path
const __dirname = dirname(__filename);

/** @returns {webpack.Configuration} */
const config = (a, env) => ({
  devtool: "cheap-source-map",
  devtool: env.mode === "production" ? undefined : "cheap-source-map",
  resolve: {
    extensions: [".js"],
  },
  entry: {
    background: join(__dirname, "./background.js"),
    content: join(__dirname, "./content.js"),
  },
  output: {
    environment: {
      dynamicImport: true,
    },
  },
  plugins: [
    new WebExtension({
      background: {
        serviceWorkerEntry: "background",
        classicLoader: true,
      },
      weakRuntimeCheck: false,
    }),
  ],
  devServer: {
    hot: "only",
  },
});

export default config;
```

**Comment by Jack-Works** [comment]
> I've tried setting weakRuntimeCheck to false

Try `weakRuntimeCheck: true`, not `false`

**Comment by cezaraugusto** [comment]
No luck, same result

**Comment by Jack-Works** [comment]
thanks, I'll investigate this

**Comment by Jack-Works** [comment]
I have updated webpack-target-webextension@1.1.2 and the guide for the main world content script. Unluckily, the setup required for the main world content script is unpleasant, it requires you to set your `output.publicPath` to something like `chrome-extension://jknoiechepeohmcaoeehjaecapdplcia/dist/`.
