### ISSUE TITLE
Suggestion: Rspack support

### ISSUE THREAD

**Issue by cezaraugusto** [awesome-webextension/webpack-target-webextension#45]
Hey there! Any chance of adding support for Rspack? (https://rspack.dev/). The core package just reached version 1.0, and its API is somewhat similar to Webpack (though not similar enough to be directly compatible). I can definitely help if you’re interested. There are no similar plugins in their ecosystem at the moment.

**Comment by Jack-Works** [comment]
Hi! I am interested in supporting rspack or turbopack, but that depends on the API they provide. I didn't check any of them yet.

**Comment by cezaraugusto** [comment]
That's great news! I'm currently trying to migrate Extension.js to Rspack ([link](https://github.com/extension-js/extension.js/pull/156)). Let me know if you need a hand when you start doing it. Happy to assist with code/test/review.

**Comment by Jack-Works** [comment]
I have made some progress, but now I'm stuck at `afterOptimizeChunkIds`. rspack does not have this hook, and I need it for `eagerChunkLoading`. Without this hook, I cannot generate usable code for Manifest V3 that uses dynamic import.

**Comment by Jack-Works** [comment]
Ok, I believe I supported rspack at a very basic level. I need to do more tests and write some documents before I publish this. cc @cezaraugusto you may want to have a try, it should be there a few days later.

**Comment by cezaraugusto** [comment]
@Jack-Works that's great news! do you plan to push a pre-release version before 2.0.0?

**Comment by Jack-Works** [comment]
hi please try 2.0.0!

**Comment by Jack-Works** [comment]
See https://github.com/awesome-webextension/webpack-target-webextension/issues/49 (chunk in background service worker not loaded)
