### ISSUE TITLE
content_scripts defined in manifest.json won't update after HMR without a full reload of the web extension

### ISSUE THREAD

**Issue by Jack-Works** [awesome-webextension/webpack-target-webextension#50]

**Comment by Jack-Works** [comment]
I did some experiments on this, but it's impossible to improve this case on our side. (`content_scripts` defined in `manifest.json`).

**Comment by cezaraugusto** [comment]
@Jack-Works what are your thoughts on making a workaround for this? for cases where HMR is impossible, I'd like to fallback to a full page reload. I did some tests but applying `window.location.reload()` to content_scripts from manifest runs into an infinite refresh loop.

**Comment by Jack-Works** [comment]
@cezaraugusto The JS file specified in the manifest.json will not update even if the webpage is reloaded. It has to be an extension reload. I tried chrome.scripting API to re-register the content script it also doesn't work. I have no clue for this now
